server:
  port: 8083
  servlet:
    context-path: /auth
    
spring: 
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource: 
    url: jdbc:mysql://localhost:3306/auth?useTimezone=true&serverTimezone=GMT-3
    username: root
    password: 123456

security:
  jwt:
    token:
      secret-key: Nt8ZeCNMZqmPJwvz
      expire-length: 31536000000

